spring:
  security:
    oauth2:
      client:
        registration:
          strava:
            client-id: ${STRAVA_CLIENT_ID}
            client-secret: ${STRAVA_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            scope:
              - read
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete # Required by Strava
            user-name-attribute: id # Required by Strava

strava.baseurl: https://www.strava.com/api/v3/